name: Umoja Insights — Ingest African Economic News
on:
  schedule:
    - cron: '*/15 * * * *'  # toutes les 15 min
  workflow_dispatch:        # permet de lancer manuellement

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install feedparser sumy googletrans==4.0.0rc1 requests

      - name: Run ingestion
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: python ingest.py
